Repository collab-community/journey-book, pull requests merged in 2022-07, with the labels that each got.

#60 chore: Created my Journey
  Data.json
  journeys/EbukaChuqz.md
Labels: size/M

#61 fix: dependabot alerts
  bs-config.json
  package-lock.json
  package.json
Labels: size/S

#63 make shourgamer2.tk#Projects
  journeys/shourgamer2.md
Labels: size/XS

#64 Fixed the mail !
  journeys/sambhavgupta0705.md
Labels: size/XS

#65 fix: rename EbukaChuqz.md to ebukachuqz.md
  journeys/ebukachuqz.md
Labels: size/XS

#66 assign journey book team
  .github/CODEOWNERS
Labels: enhancement, size/XS

#69 grammar/spelling in readme
  README.md
Labels: documentation, enhancement, size/S

#71 docs: improve readme
  README.md
Labels: size/M

#72 Update Data.json
  Data.json
  journeys/Abhinavkar.md
Labels: size/M

#79 fix typo in Adarsh-jaiss's Journey
  journeys/Adarsh-jaiss.md
Labels: documentation, size/XS

#80 fix grammer, typos, add stuff to Adarsh's journey
  journeys/Adarsh-jaiss.md
Labels: documentation, size/S

#85 Add header for Shour Gamer's Journey
  journeys/shourgamer2.md
Labels: documentation, enhancement, size/XS

#86 fix grammer in shourgamer's journey
  journeys/shourgamer2.md
Labels: documentation, size/XS

#89 Bug Fix: #70 (Updated : mobile-view docsify-darklight logo)
  style.css
Labels: size/XS

#78 created navigation.yml
  _layouts/sidebar.md
  sidebar-user-journey-navigation.yml
Labels: enhancement, size/S

#91 Create 0xCUBE.md
  Data.json
  journeys/0xCUBE.md
Labels: size/M

#84 fix grammer in Sambhav Gupta's journey
  journeys/sambhavgupta0705.md
Labels: documentation, size/XS

#87 fix grammer issue in Vikas's journey
  journeys/vikasganiga05.md
Labels: size/XS
