Repository collab-community/journey-book, pull requests merged in 2022-09, with the labels that each got.

#134 Favicon update
  184179878-38e8674d-4307-4030-90e7-e265da167437.ico
  184179878-38e8674d-4307-4030-90e7-e265da167437.png
Labels: size/XS

#133 Added AbbeyIT journey
  Data.json
  journeys/AbbeyIT.md
Labels: size/M

#136 Added My Journey
  Data.json
  journeys/RohitRajvaidya5.md
Labels: size/M

#138 Fix: Changed the text color from light gray to black in light mode
  main.js
Labels: size/M

#139 Added my Journey so far
  Data.json
  journeys/404Nikhil.md
  journeys/AbbeyIT.md
Labels: size/S

#140 updated README.md
  journeys/Adarsh-jaiss.md
Labels: size/XS, Hacktoberfest, hacktoberfest-accepted
