Repository collab-community/journey-book, pull requests merged in 2022-08, with the labels that each got.

#95 Add new journey
  Data.json
  journeys/Pericles001.md
Labels: size/L

#83 Fix grammer issue with Ebuka's journey
  journeys/ebukachuqz.md
Labels: documentation, size/S

#82 Fix grammer in Aryav's journey
  journeys/aryav-v.md
Labels: documentation, size/XS

#97 my journey as a developer
  Data.json
  journeys/AzeezTM.md
Labels: size/M

#96 Added Journey of Agrim-Sharma174
  Data.json
  journeys/Agrim-Sharma174.md
Labels: size/M

#105 feat: dynamic favicon for user journeys
  favicon.ico
  index.html
  main.js
Labels: size/M

#107 Reviewed all the changes
  Data.json
  journeys/ayushigeorge31.md
Labels: size/S

#109 feat: update user cards on home page
  index.md
  style.css
Labels: size/M

#110 Journey of SandeepUrankar added.
  Data.json
  journeys/SandeepUrankar.md
Labels: size/S

#113 Create PrateekSrivastava.md
  Data.json
  journeys/PrateekSrivastava.md
Labels: size/M

#116 Edit Prateek-Srivastav.md
  journeys/Prateek-Srivastav.md
Labels: size/S

#118 Change darkmode color from darkesh blue to Matte Black
  darkmode.js
  favicon.png
  index.html
Labels: enhancement, size/XS

#111 Leave space between text for Ayushi's Journey
  journeys/ayushigeorge.md
Labels: size/XS

#121 fixed the white background issue
  Data.json
  journeys/namyakhan.md
  main.js
  package-lock.json
Labels: size/S

#122 Favicon change
  assets/favicon.ico
  index.html
Labels: size/XS

#124 Journey added
  Data.json
  journeys/kelvinparmar.md
Labels: size/M

#123 Move Gitpod to Navbar instead of after text.
  _layouts/navbar.md
  index.md
Labels: size/XS

#127 Aditya Joshi journey added
  Data.json
  journeys/adityajoshi-08.md
Labels: size/M

#129 [DOCS] correct file location of the documentations
  README.md
Labels: size/XS

#131 Added Amarnath's Journey.
  Data.json
  journeys/fluentmoheshwar.md
Labels: size/M

#132 Added a summary of my journey and my contact links
  Data.json
  journeys/Badbatunde.md
Labels: size/M
