Repository collab-community/journey-book, pull requests merged in 2022-10, with the labels that each got.

#142 Added about Hritesh journey
  Data.json
  journeys/hritesh94.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#144 ayush added a file name ayushrtwt in journeys folder
  journeys/ayushrtwt.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#146 Updation
  Data.json
  journeys/akshatmishra25.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#154 Added Ritika Agrawal's Journey
  Data.json
  journeys/Abhinavkar.md
  journeys/Ritika-Agrawal811.md
  package-lock.json
Labels: size/M

#149 Added my Journey
  journeys/divasgt.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#141 Aishwar's jounrey added
  Data.json
  journeys/mrworld196wide.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#150 Added my profile data
  Data.json
Labels: size/XS

#155 ayush made a change in Data.json
  Data.json
Labels: size/XS

#156 Added sohail60.md to Journey
  Data.json
  journeys/sohail60.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#157 Added Arpit Ghura Journey
  Data.json
  journeys/arpitghura.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#159 Add Rafaela's Journey
  Data.json
  journeys/GRISONRF.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#161 ADD: added my journey
  Data.json
  journeys/Ashish-khanagwal.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#162 added Pratap's Journey
  Data.json
  journeys/pratap360.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#164 Updated my journey and added my details.
  Data.json
  journeys/manishpoko.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#166 My journey
  Data.json
  journeys/Heismanish.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#174 Removed projects
  journeys/Adarsh-jaiss.md
Labels: size/XS, Hacktoberfest, hacktoberfest-accepted

#147 Add hover effect to user-card
  style.css
Labels: size/S

#169 Update Data.json
  Data.json
Labels: size/XS

#170 Create likhith4.md
  journeys/likhith4.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#158 added journey- bugsy
  Data.json
  journeys/bugsyy157.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#163 added Pranit.md file
  Data.json
  journeys/Pranit-02.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#148 update Data.json
  Data.json
  journeys/AyushSarode.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#171 Added ausie8526.md
  Data.json
  journeys/ausie8526.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#172 new journey: Deepanshu0810
  Data.json
  journeys/Deepanshu0810.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#173 new journey: Paramhans-Singh
  Data.json
  journeys/Paramhans-Singh.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#177 Added vita-tran.md to the journeys directory and information into Data.json
  Data.json
  journeys/vita-tran.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#175 Added Savijain.md
  Data.json
  journeys/Savijain.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#178 hugekontrast added his profile.
  Data.json
  journeys/hugekontrast.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#182 Added Aayushi Mittal's Journey
  Data.json
  journeys/Aayushi-Mittal.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#176 Ahnafahamed
  Data.json
  journeys/AhnafAhamed.md
Labels: size/M

#189 Added Anikurhade To Journey Book
  Data.json
  journeys/anikurhade.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#188 minor changes in my journey folder
  journeys/ayushrtwt.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#187 Update Data.json
  Data.json
Labels: size/XS, Hacktoberfest, hacktoberfest-accepted

#180 Created new file ShivamPathak99.md and updated Data.json
  Data.json
  journeys/ShivamPathak99.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#192 done
  Data.json
  journeys/Karan9616.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#193 Gaurav Lonari Journey Added
  Data.json
  journeys/gauravlonari.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#191 Data added
  Data.json
  journeys/anjali112-bit.md
Labels: size/M, Hacktoberfest, hacktoberfest-accepted

#196 Updated README.md
  README.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#202 Create Rohit.md
  journeys/Rohit.md
Labels: size/S, Hacktoberfest, hacktoberfest-accepted

#203 Update Data.json
  Data.json
Labels: size/XS, Hacktoberfest, hacktoberfest-accepted
